"""
Metrics infrastructure for Product Service.

Provides Prometheus metrics for monitoring.
"""

from .prometheus import (
    HTTP_REQUESTS_TOTAL,
    HTTP_REQUEST_DURATION,
    PRODUCTS_TOTAL,
    PRODUCTS_BY_STATUS,
    PRODUCTS_BY_SOURCE,
    KAFKA_MESSAGES_CONSUMED,
    KAFKA_CONSUMER_LAG,
    ENRICHMENT_REQUESTS,
    ENRICHMENT_DURATION,
    DB_CONNECTIONS_ACTIVE,
    DB_QUERY_DURATION,
)

__all__ = [
    "HTTP_REQUESTS_TOTAL",
    "HTTP_REQUEST_DURATION",
    "PRODUCTS_TOTAL",
    "PRODUCTS_BY_STATUS",
    "PRODUCTS_BY_SOURCE",
    "KAFKA_MESSAGES_CONSUMED",
    "KAFKA_CONSUMER_LAG",
    "ENRICHMENT_REQUESTS",
    "ENRICHMENT_DURATION",
    "DB_CONNECTIONS_ACTIVE",
    "DB_QUERY_DURATION",
]
