"""
Raw Product Model.

Data model for scraped product information from construction material stores.
"""
from dataclasses import dataclass, field, asdict
from datetime import datetime
from typing import Optional, Dict, Any, List
from uuid import uuid4


@dataclass
class RawProduct:
    """
    Raw product data scraped from a construction material store.
    
    This model represents the raw, unprocessed product data that will be
    sent to the Product Service for ingestion and AI enrichment.
    """
    
    # Unique identifier (generated by parser)
    id: str = field(default_factory=lambda: str(uuid4()))
    
    # Source information
    source_url: str = ""
    source_name: str = ""  # e.g., "leroymerlin.ru", "sdvor.com"
    
    # Basic product information
    name_original: str = ""
    brand: Optional[str] = None
    category_breadcrumbs: Optional[List[str]] = None
    
    # Product attributes (specifications)
    attributes: Optional[List[Dict[str, Any]]] = None
    
    # Documents and images
    documents: Optional[List[Dict[str, str]]] = None  # PDF certificates, manuals
    images: Optional[List[str]] = None
    
    # Price information
    price_amount: Optional[float] = None
    price_currency: Optional[str] = "RUB"
    
    # Availability
    availability: Optional[str] = None  # "in_stock", "out_of_stock", "pre_order"
    
    # Structured data (if available)
    schema_org_data: Optional[Dict[str, Any]] = None  # JSON-LD Schema.org data
    next_data: Optional[Dict[str, Any]] = None  # __NEXT_DATA__ for Next.js sites
    
    # Metadata
    scraped_at: str = field(default_factory=lambda: datetime.utcnow().isoformat())
    parser_version: str = "1.0.0"
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary for serialization."""
        return asdict(self)
    
    def to_kafka_event(self) -> Dict[str, Any]:
        """Convert to Kafka event format."""
        return {
            "event_type": "raw_product",
            "event_id": self.id,
            "timestamp": self.scraped_at,
            "payload": self.to_dict(),
        }
